-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "ActivityType" ADD VALUE 'TASK_PRIORITY_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_DUE_DATE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_WATCHER_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_WATCHER_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_DEPENDENCY_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_DEPENDENCY_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_MOVED_TO_SPRINT';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_TIME_LOGGED';
ALTER TYPE "ActivityType" ADD VALUE 'PROJECT_ARCHIVED';
ALTER TYPE "ActivityType" ADD VALUE 'PROJECT_MEMBER_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'PROJECT_MEMBER_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'PROJECT_STATUS_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE 'SPRINT_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'SPRINT_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'SPRINT_CANCELLED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKSPACE_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKSPACE_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKSPACE_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKSPACE_MEMBER_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKSPACE_MEMBER_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'ORGANIZATION_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'ORGANIZATION_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'ORGANIZATION_MEMBER_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'ORGANIZATION_MEMBER_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKFLOW_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKFLOW_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKFLOW_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'STATUS_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'STATUS_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'STATUS_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'TRANSITION_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'TRANSITION_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'LABEL_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'LABEL_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'LABEL_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'INBOX_CONFIGURED';
ALTER TYPE "ActivityType" ADD VALUE 'INBOX_MESSAGE_RECEIVED';
ALTER TYPE "ActivityType" ADD VALUE 'INBOX_MESSAGE_CONVERTED';
ALTER TYPE "ActivityType" ADD VALUE 'INBOX_RULE_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'INBOX_RULE_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'EMAIL_ACCOUNT_CONNECTED';
ALTER TYPE "ActivityType" ADD VALUE 'EMAIL_SYNC_COMPLETED';
ALTER TYPE "ActivityType" ADD VALUE 'AUTOMATION_RULE_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'AUTOMATION_RULE_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'AUTOMATION_RULE_EXECUTED';
ALTER TYPE "ActivityType" ADD VALUE 'AUTOMATION_RULE_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'USER_ROLE_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE 'INVITATION_SENT';
ALTER TYPE "ActivityType" ADD VALUE 'INVITATION_ACCEPTED';
ALTER TYPE "ActivityType" ADD VALUE 'INVITATION_DECLINED';
ALTER TYPE "ActivityType" ADD VALUE 'COMMENT_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'COMMENT_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'COMMENT_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'COMMENT_REPLY_ADDED';
