import {
  Calendar,
  FileText,
  Clock,
  Hash,
  User,
  BarChart3,
  Target,
  Users,
  MessageCircle,
  Paperclip,
  Timer,
  GitBranch,
  Layers,
} from "lucide-react";

export const AVAILABLE_COLUMN_TYPES = [
  {
    id: "description",
    label: "Description",
    type: "text" as const,
    icon: FileText,
    description: "Task description",
  },
  {
    id: "taskNumber",
    label: "Task Number",
    type: "number" as const,
    icon: Hash,
    description: "Task number/ID",
  },
  {
    id: "timeline",
    label: "Timeline",
    type: "dateRange" as const,
    icon: Calendar,
    description: "Start and due dates",
  },
  {
    id: "completedAt",
    label: "Completed Date",
    type: "date" as const,
    icon: Calendar,
    description: "Task completion date",
  },
  {
    id: "storyPoints",
    label: "Story Points",
    type: "number" as const,
    icon: Target,
    description: "Story point estimation",
  },
  {
    id: "originalEstimate",
    label: "Original Estimate",
    type: "number" as const,
    icon: Clock,
    description: "Original time estimate",
  },
  {
    id: "remainingEstimate",
    label: "Remaining Estimate",
    type: "number" as const,
    icon: BarChart3,
    description: "Remaining time estimate",
  },
  {
    id: "reporter",
    label: "Reporter",
    type: "user" as const,
    icon: Users,
    description: "Task reporter/creator",
  },
  {
    id: "updatedBy",
    label: "Updated By",
    type: "user" as const,
    icon: User,
    description: "User who last updated the task",
  },
  {
    id: "createdAt",
    label: "Created Date",
    type: "date" as const,
    icon: Calendar,
    description: "Task creation date",
  },
  {
    id: "updatedAt",
    label: "Updated Date",
    type: "date" as const,
    icon: Calendar,
    description: "Last update date",
  },
  {
    id: "sprint",
    label: "Sprint",
    type: "text" as const,
    icon: GitBranch,
    description: "Associated sprint",
  },
  {
    id: "parentTask",
    label: "Parent Task",
    type: "text" as const,
    icon: Layers,
    description: "Parent task reference",
  },
  {
    id: "childTasksCount",
    label: "Child Tasks",
    type: "number" as const,
    icon: Layers,
    description: "Number of child tasks",
  },
  {
    id: "commentsCount",
    label: "Comments",
    type: "number" as const,
    icon: MessageCircle,
    description: "Number of comments",
  },
  {
    id: "attachmentsCount",
    label: "Attachments",
    type: "number" as const,
    icon: Paperclip,
    description: "Number of attachments",
  },
  {
    id: "timeEntries",
    label: "Time Entries",
    type: "number" as const,
    icon: Timer,
    description: "Number of time entries",
  },
];
